openapi: 3.0.0
info:
  title: Estates API
  description: API for retrieving information about estates
  version: 1.0.0
servers:
  - url: http://{domain}:{port}/api/v1
    description: Development Server
    variables: 
      domain:
        default: localhost
      port:
        default: '5000'
paths:
  /estates:
    get:
      summary: Get Estates
      description: |
        This endpoint allows you to retrieve a list of estates.
        Optional filters can be applied to refine the search.
      parameters:
        - name: year
          in: query
          description: Filter by construction year
          schema:
            type: string
        - name: city
          in: query
          description: Filter by city
          schema:
            type: string
        - name: status
          in: query
          description: Filter by status
          schema:
            type: string
            enum:
              - en_venta
              - pre_venta
              - vendido
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: array
                    items:
                      type: object
                      properties:
                        address:
                          type: string
                          description: Address of the estate
                        city:
                          type: string
                          description: City of the estate
                        description:
                          type: string
                          description: Description of the estate
                        price:
                          type: number
                          description: Price of the estate
                        status:
                          type: string
                          description: Status of the estate
